#!/usr/bin/env python3
import os
import sys

# Hmm.... https://www.irishpost.com/life-style/infamous-no-irish-no-blacks-no-dogs-signs-may-never-have-existed-racist-xenophobic-148416
NO_IRISH_NEED_APPLY = [
    "README.md",
    "index.md",
]

TRUE_FROM_A_CERTAIN_POINT_OF_VIEW = [
    "true",
    "yes",
    "on",
    "1",
]
COMMENT_START = "<!--"
COMMENT_END = "-->"

CENSORED_COMMENTS = """
 &nbsp;

<script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-database.js"></script>
<script src="https://jpedro.github.io/js/v1/data.js"></script>
<script src="https://jpedro.github.io/js/v1/comments.js"></script>
<script defer="">Comments.mount(document.body.children[0]);</script>
"""

SHOW_ME_SOME_MCLOVIN = """
<br />
<br />
<!-- #  &nbsp; -->

<!-- Made with some <3 [Not a lot](https://github.com/jpedro/jpedro.github.io) -->
<!-- Posts nobody asked for <font color="red" size="1px">■</font> -->
Made with some <3 but not a lot.
"""

TEMPLATE_INDEX = """
# Index
<!-- # Posts nobody asked for -->

<!-- # Index -->
<!--  &nbsp; -->

{{ pages }}

""" # + TEMPLATE_COMMENTS

# #### Tags
# {{ tags }}


TEMPLATE_TAG = """
## {{ name }}

{{ content }}

"""

def green(text: str) -> str:
    return f"\033[32;1m{text}\033[0m"




class Index:

    def load(self, path: str) -> dict:
        lines = open(path, "r").readlines()
        attrs = {}

        for line in lines:
            line = line.strip()

            if line.find("# ") == 0:
                if attrs.get("title") is None:
                    print(f"==> Using first '#' header as title: {line}")
                    attrs["title"] = line[2:]
                else:
                    print(f"==> Skip. Using previous title: {attrs['title']}")
                continue

            start = line.find(COMMENT_START)
            end = line.find(COMMENT_END)
            if start < 0:
                continue
            if end < 0:
                continue

            # print(f"Found line: {line}")
            comment = line[len(COMMENT_START):len(
                line) - len(COMMENT_END)].strip()
            # print(f"  Comment: {comment}")

            pos = comment.find(":")
            if pos < 0:
                attrs[comment] = True
                continue

            key = comment[0:pos].strip()
            val = comment[pos+1:].strip()
            # print(f"  {key}: {val}")
            attrs[key] = val

        print(f"==> Found attrs in file {path}: {attrs}")
        return attrs


    def titlelize(self, text: str) -> str:
        return text[0].upper() + text[1:]


    def replaceFooter(self, path: str, comments):
        with open(path, "r") as f:
            text = f.read()

        startFooter = "<!-- START FOOTER -->"
        endFooter = "<!-- END FOOTER -->"
        posStart = text.find(startFooter)
        posEnd = text.find(endFooter)
        print(f"posStart: {posStart}")
        print(f"posEnd: {posEnd}")
        print(f"lenEnd: {len(endFooter)}")

        if posStart < 0:
            print(f"Failed to find {startFooter}")
            before = text
            after = ""

        elif posEnd < 0:
            print(f"Failed to find {endFooter}")
            before = text
            after = ""

        else:
            cutRest = posEnd + len(endFooter)
            before = text[0:posStart]
            after = text[cutRest:]


        # print(f"comments: {comments}")
        # if comments == "false":
        #     text = f"{before}{after}"
        #     print(green("Not adding comments"))
        # else:
        #     middle = f"{startFooter}{TEMPLATE_COMMENTS}{endFooter}"
        #     text = f"{before}{middle}{after}"

        with open(path, "w") as f:
            f.write(text)


    def replaceTags(self, path: str, tags: list):
        with open(path, "r") as f:
            text = f.read()

        startTags = "<!-- START TAGS -->"
        endTags = "<!-- END TAGS -->"
        posStart = text.find(startTags)
        posEnd = text.find(endTags)
        print(f"posStart: {posStart}")
        print(f"posEnd: {posEnd}")
        print(f"lenEnd: {len(endTags)}")

        if posStart < 0:
            print(f"Failed to find {startTags}")
            return

        if posEnd < 0:
            print(f"Failed to find {endTags}")
            return

        cutRest = posEnd + len(endTags)
        print(f"Found start: {posStart}, end: {posEnd}, cut: {cutRest}")
        before = text[0:posStart]
        after = text[cutRest:]
        badges = []
        badges.append(startTags)
        for tag in tags:
            clean = tag.replace(" ", "-")
            badges.append(
                f'[<img src="https://img.shields.io/badge/Tag-{tag}-brightgreen">](/tags/{clean})'
            )
        badges.append(endTags)
        middle = "\n".join(badges)

        text = f"{before}{middle}{after}"
        with open(path, "w") as f:
            f.write(text)


    def process(self, save: bool):
        blogPages = {}
        blogTags = {}

        for path in os.listdir():
            ext = path[len(path)-3:]
            if ext != ".md":
                continue
            if path in NO_IRISH_NEED_APPLY:
                continue

            print(f"==> Found file {green(path)}")
            # if path == "dispatch.md":

            attrs = self.load(path)
            if str(attrs.get("hidden")).lower() in TRUE_FROM_A_CERTAIN_POINT_OF_VIEW:
                print(f"==> File {green(path)} is hidden")
                continue

            if not attrs.get("title"):
                title = os.path.basename(path).replace(".md", "").replace("-", " ")
                attrs["title"] = self.titlelize(title)
                print(f"==> Using file {green(path)} name as title: {title}")

            tags = attrs.get("tags")
            pageTags = []
            if tags:
                for tag in attrs["tags"].split(","):
                    tag = tag.strip()
                    if blogTags.get(tag) is None:
                        blogTags[tag] = {}
                    pageTags.append(tag)
                    blogTags[tag][path] = attrs["title"]

            self.replaceTags(path, pageTags)
            self.replaceFooter(path, attrs.get("comments", "true"))

            blogPages[path] = attrs["title"]

        print(f"==> Using pages {blogPages}")
        print(f"==> Using tags {blogTags}")

        separator = "─" * 80
        tagItems = {}
        os.makedirs(f"tags", exist_ok=True)
        for tag, pages in blogTags.items():
            tagItems[tag] = []
            content = []
            clean = tag.replace(" ", "-")
            # print(f"\nTag: {titlelize(tag)}")
            for page, title in pages.items():
                tagItems[tag].append(page)
                # print(f"- Page: {title}: {page}")
                # content.append(f"- [{title}](../{page[0:len(page)-3]})")
                content.append(f"- [{title}](../{page})")
                # content.append(f"- [{title}](/{page})")

            text = TEMPLATE_TAG.replace("{{ name }}", self.titlelize(tag))
            text = text.replace("{{ content }}", "\n".join(content)).strip()
            print()
            print(f"File tags/{green(tag)}.md")
            print("\033[38;5;242m" + separator)
            print(text)
            print(separator + "\033[0m")
            if save:
                os.makedirs(f"tags", exist_ok=True)
                with open(f"tags/{clean}.md", "w") as f:
                    f.write(text)

        content = []
        for name, title in blogPages.items():
            # print(f"- {title}: {name}")
            # content.append(f"- [{title}]({name})")
            # content.append(f"- [{title}]({name[0:len(name)-3]})")
            content.append(f"- [{title}]({name})")

        tagsContent = []
        # print(tagItems)
        for tag, pages in tagItems.items():
            count = len(pages)
            # print(f"- Tag: {tag}: {count}")
            tagsContent.append(f"- [{tag}](tags/{tag}) ({count})")

        print("tagsContent", tagsContent)
        text = TEMPLATE_INDEX.replace("{{ pages }}", "\n".join(content))
        text = text.replace("{{ tags }}", "\n".join(tagsContent)).strip()
        print()
        print("File \033[32;1mindex.md")
        print("\033[38;5;242m" + separator)
        print(text)
        print(separator + "\033[0m")
        if save:
            with open("index.md", "w") as f:
                f.write(text)
                f.write(SHOW_ME_SOME_MCLOVIN)


if __name__ == "__main__":
    index = Index()
    save = True if "--save" in sys.argv else False
    index.process(save)
