name: Don't you dare!
run-name: You dared!!! [${{ github.ref }}] ${{ inputs.SHA || github.sha }}

on:
  workflow_dispatch:
    inputs:
      SHA:
        type: string
        description: Something something

env:
  AWS_REGION : "eu-west-1"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  assume:
    name: Assumptions...
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4

      - name: I'm doing it!
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_LOGIN }}
          role-session-name: i-am-daring
          aws-region: ${{ env.AWS_REGION }}
