name: Don't you dare!
run-name: YOOOU dared!!! [${{ github.ref }}] ${{ inputs.SHA || github.sha }}

on:
  workflow_dispatch:
    inputs:
      SHA:
        type: string
        description: Something something

env:
  AWS_REGION : "eu-west-1"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  assume:
    name: Assumptions...
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4

      - name: Debugs
        run: |
          # echo "export"
          # echo "---"
          export
          # echo ""==="

      - name: I'm doing it!
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_LOGIN }}
          role-session-name: i-am-daring
          aws-region: ${{ env.AWS_REGION }}

      - name: Of course this wouldn't work...
        if: always()
        run: |
          echo "What did you expect?"

      - name: VW fix
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            console.log(github);
            console.log(context);
            console.log(core);
            if (core.isDebug()) {
              core.warning('The debug message will be skipped.');
            } else {
              core.debug('This is a debug message.');
            }
            core.info('This is an info.')
            core.notice('What does this do?')
            core.warning('This is a warning!');
            core.error('This is bad, action may still succeed though.')
            core.setOutput('outputKey', 'outputVal');
            core.exportVariable('envVar', 'Val');
