name: Index pages

on:
  push:
    branches:
    - master


jobs:
  index:
    name: Index pages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Rebuild index.md
      run: |
        python index.py --save

    - name: Commit to master
      run: |
        echo "==> Setting up local user"
        git config --local user.email "actions@github.com"
        git config --local user.name  ${{ github.actor }}

        echo "==> Adding all changes"
        git add . || echo "==> No changes"

        echo "==> Checking the status"
        git status

        echo "==> Commiting"
        git commit -m "Indexing pages" || echo "==> All is committed"
        git fetch origin master

        echo "==> Rebasing"
        git rebase origin/master || echo "==> Already up to date"

        echo "==> Pushing"
        git push origin HEAD || echo "==> Already pushed"
