name: Index

on:
  push:
    branches:
    - master


jobs:
  index:
    name: Index
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      # with:
      #   python-version: "3.11"

    - name: Process posts
      run: |
        ./.github/scripts/posts.py

    # - name: Commit
    #   run: |
    #     echo "==> Setting up local user"
    #     git config --local user.email "actions@github.com"
    #     git config --local user.name  ${{ github.actor }}

    #     echo "==> Adding all changes"
    #     git add . || echo "==> No changes. Hmm"

    #     echo "==> Checking the status"
    #     git status

    #     echo "==> Commiting"
    #     git commit -m "$(curl -sfL https://whatthecommit.com/index.txt || echo 'Indexing pages')" || echo "==> No changes. Hmm"
    #     git fetch origin master

    #     echo "==> Rebasing"
    #     git rebase origin/master || echo "==> Already up to date"

    #     echo "==> Pushing"
    #     git push origin HEAD || echo "==> Already pushed"
