name: Rusty

on:
  push:
    branches:
    - master


jobs:
  index:
    name: Does stuff
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Run
      run: |
        cargo run -- --name NAME --count 2 --prefix "PREFIX:"
